name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - name: test
        env:
          DATABASE_URL: mysql://root:example@host.docker.internal:3306/
          NEXT_PUBLIC_URL: http://localhost:3000/
          IRON_SESSION_SECRET: 12345678900987654321234567898989898989898989898989898
        run: npm run test
