name: Deployer
on: 
  push:
    branches: [' main ']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: techship
          path: .
  testing:
    runs-on: ubuntu-latest
    needs: build
    environment: testing
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: techship
          path: .
      - name: Deploy to testing
        uses: ls ./techship
  
  production:
    runs-on: ubuntu-latest
    needs: testing
    environment: production
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: techship
          path: .
      - name: Deploy to production
        uses: ls ./techship
    
